attributes = {
    "AAPL": {
        "RANDOM_FOREST_md": 2,
        "RANDOM_FOREST_ne": 2,
        "LSTM_un": 200,
        "LSTM_ep": 25,
        "XGB_lr": 0.5,
        "XGB_ne": 10,
        "XGB_md": 5,
    },
    "AMZN": {
        "RANDOM_FOREST_md": 4,
        "RANDOM_FOREST_ne": 2,
        "LSTM_un": 200,
        "LSTM_ep": 25,
        "XGB_lr": 0.5,
        "XGB_ne": 20,
        "XGB_md": 10,
    },
    "GOOG": {
        "RANDOM_FOREST_md": 4,
        "RANDOM_FOREST_ne": 2,
        "LSTM_un": 200,
        "LSTM_ep": 25,
        "XGB_lr": 0.5,
        "XGB_ne": 10,
        "XGB_md": 15,
    },
    "GOOGL": {
        "RANDOM_FOREST_md": 4,
        "RANDOM_FOREST_ne": 2,
        "LSTM_un": 200,
        "LSTM_ep": 25,
        "XGB_lr": 0.5,
        "XGB_ne": 10,
        "XGB_md": 15,
    },
    "JNJ": {
        "RANDOM_FOREST_md": 3,
        "RANDOM_FOREST_ne": 2,
        "LSTM_un": 200,
        "LSTM_ep": 30,
        "XGB_lr": 0.8,
        "XGB_ne": 5,
        "XGB_md": 5,
    },
    "META": {
        "RANDOM_FOREST_md": 4,
        "RANDOM_FOREST_ne": 2,
        "LSTM_un": 200,
        "LSTM_ep": 20,
        "XGB_lr": 0.3,
        "XGB_ne": 15,
        "XGB_md": 15,
    },
    "MSFT": {
        "RANDOM_FOREST_md": 4,
        "RANDOM_FOREST_ne": 2,
        "LSTM_un": 200,
        "LSTM_ep": 25,
        "XGB_lr": 0.5,
        "XGB_ne": 10,
        "XGB_md": 10,
    },
    "NVDA": {
        "RANDOM_FOREST_md": 4,
        "RANDOM_FOREST_ne": 4,
        "LSTM_un": 200,
        "LSTM_ep": 25,
        "XGB_lr": 0.5,
        "XGB_ne": 10,
        "XGB_md": 5,
    },
    "UNH": {
        "RANDOM_FOREST_md": 3,
        "RANDOM_FOREST_ne": 2,
        "LSTM_un": 200,
        "LSTM_ep": 25,
        "XGB_lr": 0.5,
        "XGB_ne": 10,
        "XGB_md": 5,
    },
    "XOM": {
        "RANDOM_FOREST_md": 2,
        "RANDOM_FOREST_ne": 2,
        "LSTM_un": 200,
        "LSTM_ep": 25,
        "XGB_lr": 0.8,
        "XGB_ne": 10,
        "XGB_md": 15,
    },
    "JPM": {
        "RANDOM_FOREST_md": 4,
        "RANDOM_FOREST_ne": 4,
        "LSTM_un": 200,
        "LSTM_ep": 25,
        "XGB_lr": 0.5,
        "XGB_ne": 10,
        "XGB_md": 5,
    },
    "TSLA": {
        "RANDOM_FOREST_md": 3,
        "RANDOM_FOREST_ne": 4,
        "LSTM_un": 200,
        "LSTM_ep": 20,
        "XGB_lr": 0.5,
        "XGB_ne": 15,
        "XGB_md": 10,
    },
    "V": {
        "RANDOM_FOREST_md": 4,
        "RANDOM_FOREST_ne": 2,
        "LSTM_un": 200,
        "LSTM_ep": 25,
        "XGB_lr": 0.5,
        "XGB_ne": 15,
        "XGB_md": 10,
    },
    "BRKB": {
        "RANDOM_FOREST_md": 3,
        "RANDOM_FOREST_ne": 2,
        "LSTM_un": 200,
        "LSTM_ep": 30,
        "XGB_lr": 0.5,
        "XGB_ne": 10,
        "XGB_md": 5,
    },
    "PG": {
        "RANDOM_FOREST_md": 3,
        "RANDOM_FOREST_ne": 2,
        "LSTM_un": 200,
        "LSTM_ep": 30,
        "XGB_lr": 0.8,
        "XGB_ne": 10,
        "XGB_md": 15,
    },
}
